server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com #euraka服务端的实例名称
  client:
    register-with-eureka: false # false 表示不会向注册中心注册自己
    fetch-registry: false # 我自己就是服务中心，不需要去维护服务实例；并不需要去检索服务
    service-url:
      # 设置与Eureka Server交互的地址 === 查询服务 和 注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/ # 相互注册 互相守望
