server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #euraka服务端的实例名称
  client:
    register-with-eureka: false # false 表示不会向注册中心注册自己
    fetch-registry: false # 我自己就是服务中心，不需要去维护服务实例；并不需要去检索服务
    service-url:
      # 设置与Eureka Server交互的地址 === 查询服务 和 注册服务都需要依赖这个地址
      # defaultZone: http://eureka7002.com:7002/eureka/ # 相互注册 互相守望
      # 单机版：指向自己
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    # 关闭自我保护机制，使得在服务不可用时及时踢出
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000 # 响应心跳时间改为2秒